export const CREATE_SCHEDULE_ASYNC = "CREATE_SCHEDULE_ASYNC";
export const CREATE_SCHEDULE_STARTED = "CREATE_SCHEDULE_STARTED";
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS";
export const CREATE_SCHEDULE_FAILURE = "CREATE_SCHEDULE_FAILURE";
export const CREATE_SCHEDULE_RESET = "CREATE_SCHEDULE_RESET";
//delete schedule
export const DELETE_SCHEDULE_ASYNC = "DELETE_SCHEDULE_ASYNC";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAILURE = "DELETE_SCHEDULE_FAILURE";
export const DELETE_SCHEDULE_RESET = "DELETE_SCHEDULE_RESET";
//edit schedule
export const EDIT_SCHEDULE_ASYNC = "EDIT_SCHEDULE_ASYNC";
export const EDIT_SCHEDULE_SUCCESS = "EDIT_SCHEDULE_SUCCESS";
export const EDIT_SCHEDULE_FAILURE = "EDIT_SCHEDULE_FAILURE";
export const EDIT_SCHEDULE_RESET = "EDIT_SCHEDULE_RESET";
export const EDIT_SCHEDULE_STARTED = "EDIT_SCHEDULE_STARTED";
//fetch schedules
export const FETCH_SCHEDULES_ASYNC = "FETCH_SCHEDULES_ASYNC";
export const FETCH_SCHEDULES_LOADING = "FETCH_SCHEDULES_LOADING";
export const FETCH_SCHEDULES_SUCCESS = "FETCH_SCHEDULES_SUCCESS";
export const FETCH_SCHEDULES_FAILURE = "FETCH_SCHEDULES_FAILURE";
export const FETCH_SCHEDULES_RESET = "FETCH_SCHEDULES_RESET";
//detail schedule
export const FETCH_DETAIL_SCHEDULE_ASYNC = "FETCH_DETAIL_SCHEDULE_ASYNC";
export const FETCH_DETAIL_SCHEDULE_LOADING = "FETCH_DETAIL_SCHEDULE_LOADING";
export const FETCH_DETAIL_SCHEDULE_SUCCESS = "FETCH_DETAIL_SCHEDULE_SUCCESS";
export const FETCH_DETAIL_SCHEDULE_FAILURE = "FETCH_DETAIL_SCHEDULE_FAILURE";
export const FETCH_DETAIL_SCHEDULE_RESET = "FETCH_DETAIL_SCHEDULE_RESET";
//reserve seats
export const RESERVE_SEATS_ASYNC = "RESERVE_SEATS_ASYNC";
export const RESERVE_SEATS_LOADING = "RESERVE_SEATS_LOADING";
export const RESERVE_SEATS_SUCCESS = "RESERVE_SEATS_SUCCESS";
export const RESERVE_SEATS_FAILURE = "RESERVE_SEATS_FAILURE";
export const RESERVE_SEATS_RESET = "RESERVE_SEATS_RESET";
//fetch checkout
export const FETCH_CHECKOUT_ASYNC = "FETCH_CHECKOUT_ASYNC";
export const FETCH_CHECKOUT_LOADING = "FETCH_CHECKOUT_LOADING";
export const FETCH_CHECKOUT_SUCCESS = "FETCH_CHECKOUT_SUCCESS";
export const FETCH_CHECKOUT_FAILURE = "FETCH_CHECKOUT_FAILURE";
//submit payment
export const SUBMIT_PAYMENT_INFO_ASYNC = "SUBMIT_PAYMENT_INFO_ASYNC";
export const SUBMIT_PAYMENT_INFO_LOADING = "SUBMIT_PAYMENT_INFO_LOADING";
export const SUBMIT_PAYMENT_INFO_SUCCESS = "SUBMIT_PAYMENT_INFO_SUCCESS";
export const SUBMIT_PAYMENT_INFO_FAILURE = "SUBMIT_PAYMENT_INFO_FAILURE";
export const SUBMIT_PAYMENT_INFO_RESET = "SUBMIT_PAYMENT_INFO_RESET";
//cancel reservation
export const CANCEL_RESERVATION_ASYNC = "CANCEL_RESERVATION_ASYNC";
export const CANCEL_RESERVATION_SUCCESS = "CANCEL_RESERVATION_SUCCESS";
export const CANCEL_RESERVATION_RESET = "CANCEL_RESERVATION_RESET";
