export const FETCH_TICKETS_ASYNC = "FETCH_TICKETS_ASYNC";
export const FETCH_TICKETS_STARTED = "FETCH_TICKETS_STARTED";
export const FETCH_TICKETS_FAILURE = "FETCH_TICKETS_FAILURE";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_RESET = "FETCH_TICKETS_RESET";
// get ticket
export const GET_TICKET_BY_CODE_ASYNC = "GET_TICKET_BY_CODE_ASYNC";
export const GET_TICKET_BY_CODE_STARTED = "GET_TICKET_BY_CODE_STARTED";
export const GET_TICKET_BY_CODE_FAILURE = "GET_TICKET_BY_CODE_FAILURE";
export const GET_TICKET_BY_CODE_SUCCESS = "GET_TICKET_BY_CODE_SUCCESS";
export const GET_TICKET_BY_CODE_RESET = "GET_TICKET_BY_CODE_RESET";
//approve ticket
export const APPROVE_TICKET_ASYNC = "APPROVE_TICKET_ASYNC";
export const APPROVE_TICKET_STARTED = "APPROVE_TICKET_STARTED";
export const APPROVE_TICKET_SUCCESS = "APPROVE_TICKET_SUCCESS";
export const APPROVE_TICKET_FAILURE = "APPROVE_TICKET_FAILURE";
export const APPROVE_TICKET_RESET = "APPROVE_TICKET_RESET";
