export const FETCH_TICKETS_ASYNC = "FETCH_TICKETS_ASYNC";
export const FETCH_TICKETS_STARTED = "FETCH_TICKETS_STARTED";
export const FETCH_TICKETS_FAILURE = "FETCH_TICKETS_FAILURE";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_RESET = "FETCH_TICKETS_RESET";