export const CREATE_CINEMA_ASYNC = "CREATE_CINEMA_ASYNC";
export const CREATE_CINEMA_SUCCESS = "CREATE_CINEMA_SUCCESS";
export const CREATE_CINEMA_FAILURE = "CREATE_CINEMA_FAILURE";
export const CREATE_CINEMA_ATTEMPT = "CREATE_CINEMA_ATTEMPT";
export const CREATE_CINEMA_RESET = "CREATE_CINEMA_RESET"

export const FETCH_CINEMAS_ASYNC = "FETCH_CINEMAS_ASYNC";
export const FETCH_CINEMAS_LOADING = "FETCH_CINEMAS_LOADING";
export const FETCH_CINEMAS_SUCCESS = "FETCH_CINEMAS_SUCCESS";
export const FETCH_CINEMAS_FAILURE = "FETCH_CINEMAS_FAILURE";

export const DELETE_CINEMA_ASYNC = "DELETE_CINEMA_ASYNC";
export const DELETE_CINEMA_SUCCESS = "DELETE_CINEMA_SUCCESS";
export const DELETE_CINEMA_FAILURE = "DELETE_CINEMA_FAILURE";
export const DELETE_CINEMA_RESET = "DELETE_CINEMA_RESET";

export const FETCH_SINGLE_CINEMA_ASYNC = "FETCH_SINGLE_CINEMA_ASYNC";
export const FETCH_SINGLE_CINEMA_STARTED = "FETCH_SINGLE_CINEMA_STARTED";
export const FETCH_SINGLE_CINEMA_SUCCESS = "FETCH_SINGLE_CINEMA_SUCCESS";
export const FETCH_SINGLE_CINEMA_FAILURE = "FETCH_SINGLE_CINEMA_FAILURE";
export const FETCH_SINGLE_CINEMA_RESET = "FETCH_SINGLE_CINEMA_RESET";

export const EDIT_CINEMA_ASYNC = "EDIT_CINEMA_ASYNC";
export const EDIT_CINEMA_STARTED = "EDIT_CINEMA_STARTED";
export const EDIT_CINEMA_SUCCESS = "EDIT_CINEMA_SUCCESS";
export const EDIT_CINEMA_FAILURE = "EDIT_CINEMA_FAILURE";
export const EDIT_CINEMA_RESET = "EDIT_CINEMA_RESET";
