export const FETCH_USERS_ASYNC = "FETCH_USERS_ASYNC";
export const FETCH_USERS_STARTED = "FETCH_USERS_STARTED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCh_USERS_RESET = "FETCh_USERS_RESET";
//create user
export const CREATE_USER_ASYNC = "CREATE_USER_ASYNC";
export const CREATE_USER_STARTED = "CREATE_USER_STARTED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const CREATE_USER_RESET = "CREATE_USER_RESET";
//delete user
export const DELETE_USER_ASYNC = "DELETE_USER_ASYNC";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
//edit user
export const EDIT_USER_ASYNC = "EDIT_USER_ASYNC";
export const EDIT_USER_STARTED = "EDIT_USER_STARTED";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";
export const EDIT_USER_RESET = "EDIT_USER_RESET"