//fetch
export const FETCH_GENRES_ASYNC = "FETCH_GENRES_ASYNC";
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const FETCH_GENRES_FAILURE = "FETCH_GENRES_FAILURE";

//delete
export const DELETE_GENRES_ASYNC = "DELETE_GENRES_ASYNC";
export const DELETE_GENRES_SUCCESS = "DELETE_GENRES_SUCCESS";
export const DELETE_GENRES_FAILURE = "DELETE_GENRES_FAILURE";
export const DELETE_GENRES_RESET = "DELETE_GENRES_RESET";
//delete
export const CREATE_GENRE_ASYNC = "CREATE_GENRE_ASYNC";
export const CREATE_GENRE_SUCCESS = "CREATE_GENRE_SUCCESS";
export const CREATE_GENRE_FAILURE = "CREATE_GENRE_FAILURE";
export const CREATE_GENRE_RESET = "CREATE_GENRE_RESET"
