export const FETCH_DASHBOARD_ASYNC = "FETCH_DASHBOARD_ASYNC";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAILURE = "FETCH_DASHBOARD_FAILURE";
export const FETCH_DASHBOARD_STARTED = "FETCH_DASHBOARD_STARTED";
