export const CREATE_MOVIE_ASYNC = "CREATE_MOVIE_ASYNC";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAILURE = "CREATE_MOVIE_FAILURE";
export const CREATE_MOVIE_STARTED = "CREATE_MOVIE_STARTED";
export const CREATE_MOVIE_RESET = "CREATE_MOVIE_RESET";

//get movies

export const FETCH_MOVIES_ASYNC = "FETCH_MOVIES_ASYNC";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const FETCH_MOVIES_STARTED = "FETCH_MOVIES_STARTED";
export const FETCH_MOVIES_RESET = "FETCH_MOVIES_RESET";

//get single movie
export const FETCH_MOVIE_STARTED = "FETCH_MOVIE_STARTED";
export const FETCH_MOVIE_ASYNC = "FETCH_MOVIE_ASYNC";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";

//delete movie
export const DELETE_MOVIE_ASYNC = "DELETE_MOVIE_ASYNC";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILURE = "DELETE_MOVIE_FAILURE";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";

//edit movie
export const EDIT_MOVIE_STARED = "EDIT_MOVIE_STARED";
export const EDIT_MOVIE_ASYNC = "EDIT_MOVIE_ASYNC";
export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_FAILURE = "EDIT_MOVIE_FAILURE";
export const EDIT_MOVIE_RESET = "EDIT_MOVIE_RESET";

//now watching
export const FETCH_NOW_WATCHING_ASYNC = "FETCH_NOW_WATCHING_ASYNC";
export const FETCH_NOW_WATCHING_LOADING = "FETCH_NOW_WATCHING_LOADING";
export const FETCH_NOW_WATCHING_SUCCESS = "FETCH_NOW_WATCHING_SUCCESS";
export const FETCH_NOW_WATCHING_FAILURE = "FETCH_NOW_WATCHING_FAILURE";
export const FETCH_NOW_WATCHING_RESET = "FETCH_NOW_WATCHING_RESET";

//detail now watching
export const MOVIE_DETAIL_ASYNC = "MOVIE_DETAIL_ASYNC";
export const MOVIE_DETAIL_LOADING = "MOVIE_DETAIL_LOADING";
export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS";
export const MOVIE_DETAIL_FAILURE = "MOVIE_DETAIL_FAILURE";

//comming soons

export const FETCH_COMMING_SOON_ASYNC = "FETCH_COMMING_SOON_ASYNC";
export const FETCH_COMMING_SOON_LOADING = "FETCH_COMMING_SOON_LOADING";
export const FETCH_COMMING_SOON_SUCCESS = "FETCH_COMMING_SOON_SUCCESS";
export const FETCH_COMMING_SOON_FAILURE = "FETCH_COMMING_SOON_FAILURE";
export const FETCH_COMMING_SOON_RESET = "FETCH_COMMING_SOON_RESET";
